"""add_user_constrain_2

Revision ID: 0065990a4da9
Revises: 5c5c2405acf8
Create Date: 2024-09-17 01:17:17.475841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0065990a4da9"
down_revision: Union[str, None] = "5c5c2405acf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_hashed_password_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "users_hashed_password_key", "users", ["hashed_password"]
    )
    # ### end Alembic commands ###
